from pyDatalog import pyDatalog

pyDatalog.create_terms('reglas, nephentes, nombre_planta1, nombre_planta, X, Y, dionaea, sarracenia, aldrovanda, drosera, drosophyllum, triphyophyllum, darlingtonia, heliamphora, rodidula, byblis, genlisea, philcoxia, pinguicula, utricularia, cephalotus, brocchinia, catopsis')


+nephentes('abalata')
+nephentes('adnata')
+nephentes('aenigma')
+nephentes('alata')
+nephentes('alba')
+nephentes('albomarginata')
+nephentes('alpicola')
+nephentes('alzapan')
+nephentes('amabilis')
+nephentes('ampullaria')
+nephentes('anamensis')
+nephentes('andamana')
+nephentes('angasanensis')
+nephentes('appendiculata')
+nephentes('aptera')
+nephentes('argentii')
+nephentes('aristolochioides')
+nephentes('attenboroughii')
+nephentes('baramensis')
+nephentes('barcelonae')
+nephentes('beccariana')
+nephentes('bellii')
+nephentes('benstonei')
+nephentes('bicalcarata')
+nephentes('bokorensis')
+nephentes('bongso')
+nephentes('burbidgeae')
+nephentes('boschiana')
+nephentes('burkei')
+nephentes('campanulata')
+nephentes('carunculata')
+nephentes('carunculata var. robusta')
+nephentes('ceciliae')
+nephentes('chang')
+nephentes('chaniana')
+nephentes('clipeata')
+nephentes('copelandii')
+nephentes('cornuta')
+nephentes('curtisii')
+nephentes('danseri')
+nephentes('deaniana')
+nephentes('densiflora')
+nephentes('diatas')
+nephentes('distillatoria')
+nephentes('dubia')
+nephentes('edwardsiana')
+nephentes('edwardsiana subsp. macrophylla')
+nephentes('ephippiata')
+nephentes('epiphytica')
+nephentes('eustachya')
+nephentes('eymae')
+nephentes('faizaliana')
+nephentes('fallax')
+nephentes('flava')
+nephentes('fusca')
+nephentes('gantungensis')
+nephentes('geoffrayi')
+nephentes('glabrata')
+nephentes('glandulifera')
+nephentes('graciliflora')
+nephentes('gracilis')
+nephentes('gracillima')
+nephentes('gymnamphora')
+nephentes('halmahera')
+nephentes('hamata')
+nephentes('hamiguitanensis')
+nephentes('hemsleyana')
+nephentes('hirsuta')
+nephentes('hispida')
+nephentes('holdenii')
+nephentes('hurrelliana')
+nephentes('inermis')
+nephentes('insignis')
+nephentes('izumiae')
+nephentes('jacquelineae')
+nephentes('jamban')
+nephentes('justinae')
+nephentes('kampotiana')
+nephentes('kerrii')
+nephentes('khasiana')
+nephentes('klossii')
+nephentes('kongkandana')
+nephentes('krabiensis')
+nephentes('lamii')
+nephentes('lavicola')
+nephentes('leonardoi')
+nephentes('lingulata')
+nephentes('longifolia')
+nephentes('lowii')
+nephentes('macfarlanei')
+nephentes('macrophylla')
+nephentes('macrovulgaris')
+nephentes('madagascariensis')
+nephentes('mantalingajanensis')
+nephentes('mapuluensis')
+nephentes('masoalensis')
+nephentes('maxima')
+nephentes('maxima var. superba')
+nephentes('merrilliana')
+nephentes('mikei')
+nephentes('mindanaoensis')
+nephentes('minima')
+nephentes('mira')
+nephentes('mirabilis')
+nephentes('mirabilis var. echinostoma')
+nephentes('mirabilis var. globosa')
+nephentes('mirabilis var. rowanae')
+nephentes('mirabilis var. smilesii')
+nephentes('mollis')
+nephentes('monticola')
+nephentes('muluensis')
+nephentes('murudensis')
+nephentes('naga')
+nephentes('naquiyuddinii')
+nephentes('nebularum')
+nephentes('negros')
+nephentes('neoguineensis')
+nephentes('nigra')
+nephentes('northiana')
+nephentes('ovata')
+nephentes('palawanensis')
+nephentes('paniculata')
+nephentes('pantaronensis')
+nephentes('papuana')
+nephentes('parvula')
+nephentes('pectinata')
+nephentes('peltata')
+nephentes('pervillei')
+nephentes('petiolata')
+nephentes('philippinensis')
+nephentes('pilosa')
+nephentes('pitopangii')
+nephentes('platychila')
+nephentes('pulchra')
+nephentes('pyriformis')
+nephentes('rafflesiana')
+nephentes('rafflesiana var. alata')
+nephentes('rafflesiana var. elongata')
+nephentes('rafflesiana var. gigantea')
+nephentes('rafflesiana var. nivea')
+nephentes('rajah')
+nephentes('ramispina')
+nephentes('ramos')
+nephentes('reinwardtiana')
+nephentes('reinwardtiana var. samarindaensis')
+nephentes('rhombicaulis')
+nephentes('rigidifolia')
+nephentes('robcantleyi')
+nephentes('ronchinii')
+nephentes('rosea')
+nephentes('rowanae')
+nephentes('samar')
+nephentes('sanguinea')
+nephentes('saranganiensis')
+nephentes('sharifah-hapsahii')
+nephentes('sibuyanensis')
+nephentes('singalana')
+nephentes('smilesii')
+nephentes('spathulata')
+nephentes('spectabilis')
+nephentes('stenophylla')
+nephentes('sumagaya')
+nephentes('sumatrana')
+nephentes('suratensis')
+nephentes('surigaoensis')
+nephentes('talaandig')
+nephentes('talangensis')
+nephentes('tenax')
+nephentes('tentaculata')
+nephentes('tenuis')
+nephentes('thai')
+nephentes('thorelii')
+nephentes('tobaica')
+nephentes('tomoriana')
+nephentes('treubiana')
+nephentes('truncata')
+nephentes('ultra')
+nephentes('undulatifolia')
+nephentes('veitchii')
+nephentes('ventricosa')
+nephentes('vieillardii')
+nephentes('villosa')
+nephentes('viridis')
+nephentes('vogelii')
+nephentes('weda')
+nephentes('xiphioides')
+nephentes('zakriana')
+nephentes('zygon')
+aldrovanda('zygon', 'hoja', 'agua')
+byblis('aquatica', 'agua')
+byblis('filifolia', 'tierra')
+byblis('gigantea', 'tierra')
+byblis('guehoi', 'tierra')
+byblis('lamellata', 'tierra')
+byblis('liniflora', 'tierra')
+byblis('liniflora subsp. occidentalis', 'tierra')
+byblis('pilbarana', 'tierra')
+byblis('rorida', 'tierra')
+cephalotus('cephalotus follicularis', 'jarro')
+darlingtonia('californica', 'cobra')
+darlingtonia('californica f. viridiflora', 'cobra')
+dionaea('muscipula', 'diente')
+dionaea('muscipula f. erecta', 'diente')
+dionaea('muscipula f. erigée', 'diente')
+dionaea('muscipula f. filiformis', 'diente')
+dionaea('muscipula f. linearis', 'diente')
+dionaea('muscipula f. verte', 'diente')
+dionaea('muscipula f. viridis', 'diente')
+drosera('aberrans', 'hojas con pelos')
+drosera('acaulis', 'hojas con pelos')
+drosera('adelae', 'hojas con pelos')
+drosera('admirabilis', 'hojas con pelos')
+drosera('affinis', 'hojas con pelos')
+drosera('afra', 'hojas con pelos')
+drosera('alba', 'hojas con pelos')
+drosera('aliciae', 'hojas con pelos')
+drosera('allantostigma', 'hojas con pelos')
+drosera('amazonica', 'hojas con pelos')
+drosera('andersoniana', 'hojas con pelos')
+drosera('androsacea', 'hojas con pelos')
+drosera('anglica', 'hojas con pelos')
+drosera('anglica var. pusilla', 'hojas con pelos')
+drosera('aquatica', 'hojas con pelos')
+drosera('arcturi', 'hojas con pelos')
+drosera('arenicola', 'hojas con pelos')
+drosera('arenicola var. occidentalis', 'hojas con pelos')
+drosera('ascendens', 'hojas con pelos')
+drosera('atrostyla', 'hojas con pelos')
+drosera('aurantiaca', 'hojas con pelos')
+drosera('auriculata', 'hojas con pelos')
+drosera('australis', 'hojas con pelos')
+drosera('banksii', 'hojas con pelos')
+drosera('barbigera', 'hojas con pelos')
+drosera('barbigera subsp. barbigera', 'hojas con pelos')
+drosera('barbigera subsp. minor', 'hojas con pelos')
+drosera('barbigera subsp. silvicola', 'hojas con pelos')
+drosera('barrettorum', 'hojas con pelos')
+drosera('bequaertii', 'hojas con pelos')
+drosera('bicolor', 'hojas con pelos')
+drosera('biflora', 'hojas con pelos')
+drosera('binata', 'hojas con pelos')
+drosera('binata f. multifida', 'hojas con pelos')
+drosera('binata f. multifida f. extrema', 'hojas con pelos')
+drosera('binata var. dichotoma', 'hojas con pelos')
+drosera('binata var. dichotoma f. pedata', 'hojas con pelos')
+drosera('bindoon', 'hojas con pelos')
+drosera('brevicornis', 'hojas con pelos')
+drosera('brevifolia', 'hojas con pelos')
+drosera('broomensis', 'hojas con pelos')
+drosera('browniana', 'hojas con pelos')
+drosera('bulbigena', 'hojas con pelos')
+drosera('bulbosa', 'hojas con pelos')
+drosera('bulbosa subsp. bulbosa', 'hojas con pelos')
+drosera('bulbosa subsp. coronata', 'hojas con pelos')
+drosera('bulbosa subsp. major', 'hojas con pelos')
+drosera('burkeana', 'hojas con pelos')
+drosera('burmannii', 'hojas con pelos')
+drosera('caduca', 'hojas con pelos')
+drosera('callistos', 'hojas con pelos')
+drosera('calycina', 'hojas con pelos')
+drosera('camporupestris', 'hojas con pelos')
+drosera('capensis', 'hojas con pelos')
+drosera('capensis var. alba', 'hojas con pelos')
+drosera('capillaris', 'hojas con pelos')
+drosera('capillaris var. brasiliensis', 'hojas con pelos')
+drosera('cayennensis', 'hojas con pelos')
+drosera('cendeensis', 'hojas con pelos')
+drosera('chimaera', 'hojas con pelos')
+drosera('chrysolepis', 'hojas con pelos')
+drosera('cistiflora', 'hojas con pelos')
+drosera('cistiflora var. Eitz', 'hojas con pelos')
+drosera('citrina', 'hojas con pelos')
+drosera('citrina var. nivea', 'hojas con pelos')
+drosera('closterostigma', 'hojas con pelos')
+drosera('coalara', 'hojas con pelos')
+drosera('coccicaulis', 'hojas con pelos')
+drosera('coccipetala', 'hojas con pelos')
+drosera('collina', 'hojas con pelos')
+drosera('collinsiae', 'hojas con pelos')
+drosera('colombiana', 'hojas con pelos')
+drosera('communis', 'hojas con pelos')
+drosera('communis var. breviscapa', 'hojas con pelos')
+drosera('communis var. pauciflora', 'hojas con pelos')
+drosera('compacta', 'hojas con pelos')
+drosera('condor', 'hojas con pelos')
+drosera('cucullata', 'hojas con pelos')
+drosera('cuneifolia', 'hojas con pelos')
+drosera('curviscapa', 'hojas con pelos')
+drosera('darwinensis', 'hojas con pelos')
+drosera('depauperata', 'hojas con pelos')
+drosera('derbyensis', 'hojas con pelos')
+drosera('dichrosepala', 'hojas con pelos')
+drosera('dielsiana', 'hojas con pelos')
+drosera('dilatatopetiolaris', 'hojas con pelos')
+drosera('drummondii', 'hojas con pelos')
+drosera('echinoblastus', 'hojas con pelos')
+drosera('elongata', 'hojas con pelos')
+drosera('eneabba', 'hojas con pelos')
+drosera('enodes', 'hojas con pelos')
+drosera('eremaea', 'hojas con pelos')
+drosera('ericgreenii', 'hojas con pelos')
+drosera('ericgreenii', 'hojas con pelos')
+drosera('erythrogyne', 'hojas con pelos')
+drosera('erythrorhiza', 'hojas con pelos')
+drosera('erythrorhiza subsp. collina', 'hojas con pelos')
+drosera('erythrorhiza subsp. erythrorhiza', 'hojas con pelos')
+drosera('erythrorhiza subsp. magna', 'hojas con pelos')
+drosera('erythrorhiza subsp. squamosa', 'hojas con pelos')
+drosera('erythrorhiza var. imbecilla', 'hojas con pelos')
+drosera('erythrorhiza var. Rolystone Red', 'hojas con pelos')
+drosera('esmeraldae', 'hojas con pelos')
+drosera('esperensis', 'hojas con pelos')
+drosera('esterhuyseniae', 'hojas con pelos')
+drosera('falconeri', 'hojas con pelos')
+drosera('felix', 'hojas con pelos')
+drosera('filiformis', 'hojas con pelos')
+drosera('filiformis var. filiformis', 'hojas con pelos')
+drosera('filiformis var. tracyi', 'hojas con pelos')
+drosera('fimbriata', 'hojas con pelos')
+drosera('finlaysoniana', 'hojas con pelos')
+drosera('flexicaulis', 'hojas con pelos')
+drosera('foliosa', 'hojas con pelos')
+drosera('fragrans', 'hojas con pelos')
+drosera('fulva', 'hojas con pelos')
+drosera('geniculata', 'hojas con pelos')
+drosera('gibsonii', 'hojas con pelos')
+drosera('gigantea', 'hojas con pelos')
+drosera('gigantea subsp. gigantea', 'hojas con pelos')
+drosera('gigantea var. geniculata', 'hojas con pelos')
+drosera('glabripes', 'hojas con pelos')
+drosera('glabriscapa', 'hojas con pelos')
+drosera('glanduligera', 'hojas con pelos')
+drosera('gracilis', 'hojas con pelos')
+drosera('graminifolia', 'hojas con pelos')
+drosera('graniticola', 'hojas con pelos')
+drosera('grantsaui', 'hojas con pelos')
+drosera('graomogolensis', 'hojas con pelos')
+drosera('grievei', 'hojas con pelos')
+drosera('hamiltonii', 'hojas con pelos')
+drosera('hartmeyerorum', 'hojas con pelos')
+drosera('helodes', 'hojas con pelos')
+drosera('heterophylla', 'hojas con pelos')
+drosera('hilaris', 'hojas con pelos')
+drosera('hirsuta', 'hojas con pelos')
+drosera('hirtella', 'hojas con pelos')
+drosera('hirtella var. lutescens', 'hojas con pelos')
+drosera('hirticalyx', 'hojas con pelos')
+drosera('hookeri', 'hojas con pelos')
+drosera('huegelii', 'hojas con pelos')
+drosera('humbertii', 'hojas con pelos')
+drosera('humilis', 'hojas con pelos')
+drosera('hyperostigma', 'hojas con pelos')
+drosera('indica', 'hojas con pelos')
+drosera('indumenta', 'hojas con pelos')
+drosera('insolita ', 'hojas con pelos')
+drosera('intermedia', 'hojas con pelos')
+drosera('intricata', 'hojas con pelos')
+drosera('jacoby', 'hojas con pelos')
+drosera('kaieteurensis', 'hojas con pelos')
+drosera('katangensis', 'hojas con pelos')
+drosera('kenneallyi', 'hojas con pelos')
+drosera('lanata', 'hojas con pelos')
+drosera('lasiantha', 'hojas con pelos')
+drosera('latifolia', 'hojas con pelos')
+drosera('leioblastus', 'hojas con pelos')
+drosera('leucoblasta', 'hojas con pelos')
+drosera('leucostigma', 'hojas con pelos')
+drosera('linearis', 'hojas con pelos')
+drosera('liniflora', 'hojas con pelos')
+drosera('longifolia', 'hojas con pelos')
+drosera('longiscapa', 'hojas con pelos')
+drosera('lovellae', 'hojas con pelos')
+drosera('lowriei', 'hojas con pelos')
+drosera('lunata', 'hojas con pelos')
+drosera('macrantha', 'hojas con pelos')
+drosera('macrantha subsp. eremaea', 'hojas con pelos')
+drosera('macrantha subsp. planchonii', 'hojas con pelos')
+drosera('macrophylla', 'hojas con pelos')
+drosera('macrophylla subsp. monantha', 'hojas con pelos')
+drosera('madagascariensis', 'hojas con pelos')
+drosera('magna', 'hojas con pelos')
+drosera('magnifica', 'hojas con pelos')
+drosera('major', 'hojas con pelos')
+drosera('makinoi', 'hojas con pelos')
+drosera('mannii', 'hojas con pelos')
+drosera('marchantii', 'hojas con pelos')
+drosera('marchantii subsp. marchantii', 'hojas con pelos')
+drosera('marchantii subsp. prophylla', 'hojas con pelos')
+drosera('menziesii subsp. basifolia ', 'hojas con pelos')
+drosera('menziesii subsp. menziesii', 'hojas con pelos')
+drosera('menziesii subsp. penicillaris', 'hojas con pelos')
+drosera('menziesii subsp. thysanosepala', 'hojas con pelos')
+drosera('meristocaulis', 'hojas con pelos')
+drosera('micra', 'hojas con pelos')
+drosera('micrantha', 'hojas con pelos')
+drosera('microphylla', 'hojas con pelos')
+drosera('microphylla var. macropetala', 'hojas con pelos')
+drosera('microscapa', 'hojas con pelos')
+drosera('miniata', 'hojas con pelos')
+drosera('minutiflora', 'hojas con pelos')
+drosera('moanensis', 'hojas con pelos')
+drosera('modesta', 'hojas con pelos')
+drosera('monantha', 'hojas con pelos')
+drosera('montana', 'hojas con pelos')
+drosera('montana var. schwackei', 'hojas con pelos')
+drosera('montana var. tomentosa', 'hojas con pelos')
+drosera('monticola', 'hojas con pelos')
+drosera('moorei', 'hojas con pelos')
+drosera('murfetii', 'hojas con pelos')
+drosera('myriantha', 'hojas con pelos')
+drosera('nana', 'hojas con pelos')
+drosera('natalensis', 'hojas con pelos')
+drosera('neesii subsp. neesii', 'hojas con pelos')
+drosera('neocaledonica', 'hojas con pelos')
+drosera('nidiformis', 'hojas con pelos')
+drosera('nitidula', 'hojas con pelos')
+drosera('nitidula subsp. allantostigma', 'hojas con pelos')
+drosera('nitidula subsp. nitidula', 'hojas con pelos')
+drosera('nitidula subsp. omissa', 'hojas con pelos')
+drosera('nivea', 'hojas con pelos')
+drosera('oblanceolata', 'hojas con pelos')
+drosera('occidentalis', 'hojas con pelos')
+drosera('occidentalis subsp. australis', 'hojas con pelos')
+drosera('occidentalis subsp. occidentalis', 'hojas con pelos')
+drosera('occidentalis var. microscapa', 'hojas con pelos')
+drosera('omissa', 'hojas con pelos')
+drosera('orbiculata', 'hojas con pelos')
+drosera('ordensis', 'hojas con pelos')
+drosera('oreopodion', 'hojas con pelos')
+drosera('paleacea', 'hojas con pelos')
+drosera('paleacea subsp. leioblastus', 'hojas con pelos')
+drosera('paleacea subsp. paleacea', 'hojas con pelos')
+drosera('paleacea subsp. roseana', 'hojas con pelos')
+drosera('paleacea subsp. stelliflora', 'hojas con pelos')
+drosera('paleacea subsp. trichocaulis', 'hojas con pelos')
+drosera('pallida', 'hojas con pelos')
+drosera('panamensis', 'hojas con pelos')
+drosera('paradoxa', 'hojas con pelos')
+drosera('parvula', 'hojas con pelos')
+drosera('parvula subsp. sargentii', 'hojas con pelos')
+drosera('patens', 'hojas con pelos')
+drosera('pauciflora', 'hojas con pelos')
+drosera('pedicellaris', 'hojas con pelos')
+drosera('peltata', 'hojas con pelos')
+drosera('peltata subsp. auriculata', 'hojas con pelos')
+drosera('peltata var. foliosa', 'hojas con pelos')
+drosera('peltata var. glabrata', 'hojas con pelos')
+drosera('peltata var. gracilis', 'hojas con pelos')
+drosera('peltata var. nipponica', 'hojas con pelos')
+drosera('peruensis', 'hojas con pelos')
+drosera('petiolaris', 'hojas con pelos')
+drosera('pilosa', 'hojas con pelos')
+drosera('planchonii', 'hojas con pelos')
+drosera('platypoda', 'hojas con pelos')
+drosera('platystigma', 'hojas con pelos')
+drosera('porrecta', 'hojas con pelos')
+drosera('praefolia', 'hojas con pelos')
+drosera('prolifera', 'hojas con pelos')
+drosera('prophylla', 'hojas con pelos')
+drosera('prostrata', 'hojas con pelos')
+drosera('prostratoscaposa', 'hojas con pelos')
+drosera('pulchella', 'hojas con pelos')
+drosera('pumilla', 'hojas con pelos')
+drosera('purpurascens', 'hojas con pelos')
+drosera('pycnoblasta', 'hojas con pelos')
+drosera('pygmaea', 'hojas con pelos')
+drosera('quartzicola', 'hojas con pelos')
+drosera('radicans', 'hojas con pelos')
+drosera('ramellosa', 'hojas con pelos')
+drosera('ramentacea', 'hojas con pelos')
+drosera('rechingeri', 'hojas con pelos')
+drosera('regia', 'hojas con pelos')
+drosera('riparia', 'hojas con pelos')
+drosera('roraimae', 'hojas con pelos')
+drosera('roseana', 'hojas con pelos')
+drosera('rosulata', 'hojas con pelos')
+drosera('rotundifolia', 'hojas con pelos')
+drosera('rotundifolia var. corsica', 'hojas con pelos')
+drosera('rotundifolia var. furcata', 'hojas con pelos')
+drosera('rubrifolia', 'hojas con pelos')
+drosera('rubripetala', 'hojas con pelos')
+drosera('rupicola', 'hojas con pelos')
+drosera('salina', 'hojas con pelos')
+drosera('sanariapoana', 'hojas con pelos')
+drosera('sargentii', 'hojas con pelos')
+drosera('schizandra', 'hojas con pelos')
+drosera('schmutzii', 'hojas con pelos')
+drosera('schwackei', 'hojas con pelos')
+drosera('scorpioides', 'hojas con pelos')
+drosera('serpens', 'hojas con pelos')
+drosera('sessilifolia', 'hojas con pelos')
+drosera('sewelliae', 'hojas con pelos')
+drosera('silvicola', 'hojas con pelos')
+drosera('slackii', 'hojas con pelos')
+drosera('solaris', 'hojas con pelos')
+drosera('spatulata', 'hojas con pelos')
+drosera('spatulata var. bakoensis', 'hojas con pelos')
+drosera('spatulata var. gympiensis', 'hojas con pelos')
+drosera('spatulata var. loureirii', 'hojas con pelos')
+drosera('spatulata var. lovellae', 'hojas con pelos')
+drosera('spilos', 'hojas con pelos')
+drosera('spiralis', 'hojas con pelos')
+drosera('spirocalyx', 'hojas con pelos')
+drosera('squamosa', 'hojas con pelos')
+drosera('stelliflora', 'hojas con pelos')
+drosera('stenopetala', 'hojas con pelos')
+drosera('stolonifera', 'hojas con pelos')
+drosera('stolonifera subsp. compacta')
+drosera('stolonifera subsp. humilis')
+drosera('stolonifera subsp. monticola', 'hojas con pelos')
+drosera('stolonifera subsp. porrecta', 'hojas con pelos')
+drosera('stolonifera subsp. prostrata', 'hojas con pelos')
+drosera('stolonifera subsp. rupicola', 'hojas con pelos')
+drosera('stricticaulis subsp. eremaea', 'hojas con pelos')
+drosera('stricticaulis subsp. stricticaulis', 'hojas con pelos')
+drosera('subhirtella', 'hojas con pelos')
+drosera('subhirtella subsp. moorei', 'hojas con pelos')
+drosera('subhirtella subsp. subhirtella', 'hojas con pelos')
+drosera('subtilis', 'hojas con pelos')
+drosera('sulphurea', 'hojas con pelos')
+drosera('tentaculata', 'hojas con pelos')
+drosera('thysanosepala', 'hojas con pelos')
+drosera('tomentosa', 'hojas con pelos')
+drosera('tomentosa var. glabrata', 'hojas con pelos')
+drosera('toyoakensis', 'hojas con pelos')
+drosera('trichocaulis', 'hojas con pelos')
+drosera('trinervia', 'hojas con pelos')
+drosera('tubaestylis', 'hojas con pelos')
+drosera('ultramafica', 'hojas con pelos')
+drosera('uniflora', 'hojas con pelos')
+drosera('variegata', 'hojas con pelos')
+drosera('venusta', 'hojas con pelos')
+drosera('verrucata', 'hojas con pelos')
+drosera('villosa', 'hojas con pelos')
+drosera('villosa var. ascendens', 'hojas con pelos')
+drosera('viridis', 'hojas con pelos')
+drosera('walyunga', 'hojas con pelos')
+drosera('whittakeri', 'hojas con pelos')
+drosera('whittakeri subsp. aberrans', 'hojas con pelos')
+drosera('yilgarnensis', 'hojas con pelos')
+drosera('yutajensis', 'hojas con pelos')
+drosera('zeyheri', 'hojas con pelos')
+drosera('zigzagia', 'hojas con pelos')
+drosera('zonaria', 'hojas con pelos')
+drosophyllum('lusitanicum')
+genlisea('africana')
+genlisea('angolensis')
+genlisea('aurea')
+genlisea('barthlottii')
+genlisea('exhibitionista')
+genlisea('filiformis')
+genlisea('flexuosa')
+genlisea('glabra')
+genlisea('glandulosissima')
+genlisea('guianensis')
+genlisea('hispidula')
+genlisea('lobata')
+genlisea('margaretae')
+genlisea('metallica')
+genlisea('nebulicola')
+genlisea('nigrocaulis')
+genlisea('oligophylla')
+genlisea('ornata')
+genlisea('oxycentron')
+genlisea('pallida')
+genlisea('pulchella')
+genlisea('pygmaea')
+genlisea('repens')
+genlisea('roraimensis')
+genlisea('sanariapoana')
+genlisea('stapfii')
+genlisea('subglabra')
+genlisea('subviridis')
+genlisea('taylorii')
+genlisea('tuberosa')
+genlisea('uncinata')
+genlisea('violacea')
+heliamphora('arenicola', 'jarron')
+heliamphora('ceracea', 'jarron')
+heliamphora('chimantensis', 'jarron')
+heliamphora('ciliata', 'jarron')
+heliamphora('collina', 'jarron')
+heliamphora('elongata', 'jarron')
+heliamphora('exappendiculata', 'jarron')
+heliamphora('exappendiculata f. glabella', 'jarron')
+heliamphora('folliculata', 'jarron')
+heliamphora('glabra', 'jarron')
+heliamphora('heterodoxa', 'jarron')
+heliamphora('hispida', 'jarron')
+heliamphora('huberi', 'jarron')
+heliamphora('ionasi', 'jarron')
+heliamphora('macdonaldae', 'jarron')
+heliamphora('minor', 'jarron')
+heliamphora('minor f. laevis', 'jarron')
+heliamphora('minor var. pilosa', 'jarron')
+heliamphora('neblinae', 'jarron')
+heliamphora('neblinae f. parva', 'jarron')
+heliamphora('neblinae f. virdis', 'jarron')
+heliamphora('nutans', 'jarron')
+heliamphora('parva', 'jarron')
+heliamphora('pulchella', 'jarron')
+heliamphora('purpurascens', 'jarron')
+heliamphora('sarracenioides', 'jarron')
+heliamphora('tatei', 'jarron')
+heliamphora('tatei f. macdonaldae', 'jarron')
+heliamphora('tatei var. tatei', 'jarron')
+heliamphora('tyleri see H. tatei', 'jarron')
+heliamphora('uncinata', 'jarron')
+pinguicula('acuminata', 'carnosa')
+pinguicula('agnata', 'carnosa')
+pinguicula('agnata var. tamaulipensis', 'carnosa')
+pinguicula('albida', 'carnosa')
+pinguicula('algida', 'carnosa')
+pinguicula('alpina', 'carnosa')
+pinguicula('antarctica', 'carnosa')
+pinguicula('apuana', 'carnosa')
+pinguicula('balcanica', 'carnosa')
+pinguicula('balcanica subsp. pontica', 'carnosa')
+pinguicula('balcanica var. tenuilaciniata', 'carnosa')
+pinguicula('barbata', 'carnosa')
+pinguicula('benedicta', 'carnosa')
+pinguicula('bissei', 'carnosa')
+pinguicula('bohemica', 'carnosa')
+pinguicula('caerulea', 'carnosa')
+pinguicula('caerulea f. leucantha', 'carnosa')
+pinguicula('calderoniae', 'carnosa')
+pinguicula('calyptrata', 'carnosa')
+pinguicula('caryophyllacea', 'carnosa')
+pinguicula('casabitoana', 'carnosa')
+pinguicula('caudata', 'carnosa')
+pinguicula('chilensis', 'carnosa')
+pinguicula('chuquisacensis', 'carnosa')
+pinguicula('clivorum', 'carnosa')
+pinguicula('colimensis', 'carnosa')
+pinguicula('conzattii', 'carnosa')
+pinguicula('corsica', 'carnosa')
+pinguicula('corsica f. pallidula', 'carnosa')
+pinguicula('crassifolia', 'carnosa')
+pinguicula('crenatiloba', 'carnosa')
+pinguicula('crystallina', 'carnosa')
+pinguicula('crystallina subsp. hirtiflora', 'carnosa')
+pinguicula('cubensis', 'carnosa')
+pinguicula('cyclosecta', 'carnosa')
+pinguicula('debbertiana', 'carnosa')
+pinguicula('ehlersiae', 'carnosa')
+pinguicula('ehlersiae var. albiflora', 'carnosa')
+pinguicula('elizabethiae', 'carnosa')
+pinguicula('elongata', 'carnosa')
+pinguicula('emarginata', 'carnosa')
+pinguicula('esseriana', 'carnosa')
+pinguicula('filifolia', 'carnosa')
+pinguicula('fiorii', 'carnosa')
+pinguicula('flos-mulionis', 'carnosa')
+pinguicula('fontiqueriana', 'carnosa')
+pinguicula('gigantea', 'carnosa')
+pinguicula('gracilis', 'carnosa')
+pinguicula('grandiflora', 'carnosa')
+pinguicula('grandiflora f. asturiensis', 'carnosa')
+pinguicula('grandiflora f. chionopetra', 'carnosa')
+pinguicula('grandiflora f. pallida', 'carnosa')
+pinguicula('grandiflora subsp. reuteri', 'carnosa')
+pinguicula('grandiflora subsp. rosea', 'carnosa')
+pinguicula('greenwoodii', 'carnosa')
+pinguicula('gypsicola', 'carnosa')
+pinguicula('habilii', 'carnosa')
+pinguicula('hemiepiphytica', 'carnosa')
+pinguicula('heterophylla', 'carnosa')
+pinguicula('hintoniorum', 'carnosa')
+pinguicula('hirtiflora', 'carnosa')
+pinguicula('ibarrae', 'carnosa')
+pinguicula('imitatrix', 'carnosa')
+pinguicula('immaculata', 'carnosa')
+pinguicula('infundibuliformis', 'carnosa')
+pinguicula('involuta', 'carnosa')
+pinguicula('ionantha', 'carnosa')
+pinguicula('jackii', 'carnosa')
+pinguicula('jaraguana', 'carnosa')
+pinguicula('jarmilae', 'carnosa')
+pinguicula('jaumavensis', 'carnosa')
+pinguicula('jorgehintonii', 'carnosa')
+pinguicula('kondoi', 'carnosa')
+pinguicula('laueana', 'carnosa')
+pinguicula('lavalvae', 'carnosa')
+pinguicula('laxifolia', 'carnosa')
+pinguicula('leptoceras', 'carnosa')
+pinguicula('lignicola', 'carnosa')
+pinguicula('lilacina', 'carnosa')
+pinguicula('lippoldii', 'carnosa')
+pinguicula('lithophytica', 'carnosa')
+pinguicula('longifolia', 'carnosa')
+pinguicula('longifolia subsp. caussensis', 'carnosa')
+pinguicula('longifolia subsp. dertosensis', 'carnosa')
+pinguicula('longifolia subsp. longifolia f. pinetensis ', 'carnosa')
+pinguicula('longifolia subsp. reichenbachiana', 'carnosa')
+pinguicula('louisii', 'carnosa')
+pinguicula('lusitanica', 'carnosa')
+pinguicula('lutea', 'carnosa')
+pinguicula('lutea f. alba', 'carnosa')
+pinguicula('macroceras', 'carnosa')
+pinguicula('macroceras subsp. nortensis', 'carnosa')
+pinguicula('macrophylla', 'carnosa')
+pinguicula('mariae', 'carnosa')
+pinguicula('martinezii', 'carnosa')
+pinguicula('medusina', 'carnosa')
+pinguicula('mesophytica', 'carnosa')
+pinguicula('mirandae', 'carnosa')
+pinguicula('moctezumae', 'carnosa')
+pinguicula('moranensis', 'carnosa')
+pinguicula('moranensis f. flos-mulionis', 'carnosa')
+pinguicula('moranensis f. orchidioides', 'carnosa')
+pinguicula('moranensis var. alba', 'carnosa')
+pinguicula('moranensis var. caudata', 'carnosa')
+pinguicula('moranensis var. mexicana', 'carnosa')
+pinguicula('moranensis var. neovolcanica', 'carnosa')
+pinguicula('moranensis var. roseii', 'carnosa')
+pinguicula('moranensis var. superba', 'carnosa')
+pinguicula('mundi', 'carnosa')
+pinguicula('nevadensis', 'carnosa')
+pinguicula('nivalis', 'carnosa')
+pinguicula('oblongiloba', 'carnosa')
+pinguicula('orchidioides', 'carnosa')
+pinguicula('parvifolia', 'carnosa')
+pinguicula('pilosa', 'carnosa')
+pinguicula('planifolia', 'carnosa')
+pinguicula('poldinii', 'carnosa')
+pinguicula('potosiensis', 'carnosa')
+pinguicula('primuliflora', 'carnosa')
+pinguicula('pumila', 'carnosa')
+pinguicula('pumila var. buswellii', 'carnosa')
+pinguicula('pygmaea', 'carnosa')
+pinguicula('ramosa', 'carnosa')
+pinguicula('rectifolia', 'carnosa')
+pinguicula('reticulata', 'carnosa')
+pinguicula('rotundiflora', 'carnosa')
+pinguicula('sehuensis', 'carnosa')
+pinguicula('sharpii', 'carnosa')
+pinguicula('stolonifera', 'carnosa')
+pinguicula('submediterranea', 'carnosa')
+pinguicula('takakii', 'carnosa')
+pinguicula('toldensis', 'carnosa')
+pinguicula('utricularioides', 'carnosa')
+pinguicula('vallis-regiae', 'carnosa')
+pinguicula('vallisneriifolia', 'carnosa')
+pinguicula('variegata', 'carnosa')
+pinguicula('villosa', 'carnosa')
+pinguicula('vulgaris', 'carnosa')
+pinguicula('vulgaris f. albida', 'carnosa')
+pinguicula('vulgaris f. bicolor', 'carnosa')
+pinguicula('zecheri', 'carnosa')
+rodidula('dentata')
+rodidula('gorgonias')
+sarracenia('alata', 'jarron')
+sarracenia('alata f. pubescens', 'jarron')
+sarracenia('alata f. viridescens', 'jarron')
+sarracenia('alata var. atrorubra', 'jarron')
+sarracenia('alata var. cuprea', 'jarron')
+sarracenia('alata var. nigropurpurea', 'jarron')
+sarracenia('alata var. ornata', 'jarron')
+sarracenia('alata var. rubrioperculata', 'jarron')
+sarracenia('drummondii', 'jarron')
+sarracenia('flava', 'jarron')
+sarracenia('flava f. viridescens', 'jarron')
+sarracenia('flava var. atropurpurea', 'jarron')
+sarracenia('flava var. cuprea', 'jarron')
+sarracenia('flava var. maxima', 'jarron')
+sarracenia('flava var. ornata', 'jarron')
+sarracenia('flava var. rubricorpora', 'jarron')
+sarracenia('flava var. rugelii', 'jarron')
+sarracenia('leucophylla', 'jarron')
+sarracenia('leucophylla f. viridescens', 'jarron')
+sarracenia('leucophylla var. alba', 'jarron')
+sarracenia('leucophylla var. pubescens', 'jarron')
+sarracenia('minor', 'jarron')
+sarracenia('minor var. minor f. viridescens', 'jarron')
+sarracenia('minor var. okefenokeensis', 'jarron')
+sarracenia('oreophila', 'jarron')
+sarracenia('oreophila var. ornata', 'jarron')
+sarracenia('psittacina', 'jarron')
+sarracenia('psittacina f. heterophylla', 'jarron')
+sarracenia('psittacina f. viridescens', 'jarron')
+sarracenia('psittacina var. okefenokeensis', 'jarron')
+sarracenia('psittacina var. okefenokeensis f. luteoviridis', 'jarron')
+sarracenia('purpurea', 'jarron')
+sarracenia('purpurea f. heterophylla', 'jarron')
+sarracenia('purpurea f. veinless', 'jarron')
+sarracenia('purpurea subsp. purpurea var. ripicola', 'jarron')
+sarracenia('purpurea subsp. venosa', 'jarron')
+sarracenia('purpurea subsp. venosa var. burkii', 'jarron')
+sarracenia('purpurea subsp. venosa var. burkii f. luteola', 'jarron')
+sarracenia('purpurea subsp. venosa var. montana', 'jarron')
+sarracenia('purpurea subsp. venosa var. venosa f. pallidiflora', 'jarron')
+sarracenia('rosea see S. purpurea subsp. venosa var. burkii', 'jarron')
+sarracenia('rubra', 'jarron')
+sarracenia('rubra Anthocyanin Free', 'jarron')
+sarracenia('rubra subsp. alabamensis', 'jarron')
+sarracenia('rubra subsp. gulfensis', 'jarron')
+sarracenia('rubra subsp. gulfensis f. luteoviridis', 'jarron')
+sarracenia('rubra subsp. jonesii', 'jarron')
+sarracenia('rubra subsp. jonesii f. heterophylla', 'jarron')
+sarracenia('rubra subsp. jonesii f. viridescens', 'jarron')
+sarracenia('rubra subsp. wherryi', 'jarron')
+triphyophyllum('peltatum')
+utricularia('adpressa')
+utricularia('albiflora')
+utricularia('albocaerulea')
+utricularia('alpina')
+utricularia('ameliae')
+utricularia('amethystina')
+utricularia('andongensis')
+utricularia('antennifera')
+utricularia('appendiculata')
+utricularia('arcuata')
+utricularia('arenaria')
+utricularia('arnhemica')
+utricularia('asplundii')
+utricularia('aurea')
+utricularia('aureomaculata')
+utricularia('australis')
+utricularia('babui')
+utricularia('barkeri')
+utricularia('beaugleholei')
+utricularia('benjaminiana')
+utricularia('benthamii')
+utricularia('bifida')
+utricularia('biloba')
+utricularia('biovularioides')
+utricularia('bisquamata')
+utricularia('blackmanii')
+utricularia('blanchetii')
+utricularia('bosminifera')
+utricularia('brachiata')
+utricularia('brachyceras')
+utricularia('bracteata')
+utricularia('bremii')
+utricularia('breviscapa')
+utricularia('buntingiana')
+utricularia('byrneana')
+utricularia('caerulea')
+utricularia('calycifida')
+utricularia('campbelliana')
+utricularia('capilliflora')
+utricularia('cecilii')
+utricularia('cheiranthos')
+utricularia('chiakiana')
+utricularia('chiribiquetensis')
+utricularia('choristotheca')
+utricularia('christopheri')
+utricularia('chrysantha')
+utricularia('circumvoluta')
+utricularia('cochleata')
+utricularia('corneliana')
+utricularia('cornigera')
+utricularia('cornuta')
+utricularia('corynephora')
+utricularia('costata')
+utricularia('cucullata')
+utricularia('cymbantha')
+utricularia('delicatula')
+utricularia('delphinioides')
+utricularia('densiflora')
+utricularia('determannii')
+utricularia('dichotoma')
+utricularia('dimorphantha')
+utricularia('dunlopii')
+utricularia('dunstaniae')
+utricularia('endresii')
+utricularia('erectiflora')
+utricularia('exoleta')
+utricularia('fenshamii')
+utricularia('fibrosa')
+utricularia('fimbriata')
+utricularia('firmula')
+utricularia('fistulosa')
+utricularia('flaccida')
+utricularia('floridana')
+utricularia('foliosa')
+utricularia('forrestii')
+utricularia('foveolata')
+utricularia('fulva')
+utricularia('furcellata')
+utricularia('garrettii')
+utricularia('geminiloba')
+utricularia('geminiscapa')
+utricularia('geoffrayi')
+utricularia('georgei')
+utricularia('gibba')
+utricularia('graminifolia')
+utricularia('grampiana')
+utricularia('guyanensis')
+utricularia('hamiltonii')
+utricularia('helix')
+utricularia('heterochroma')
+utricularia('heterosepala')
+utricularia('hintonii')
+utricularia('hirta')
+utricularia('hispida')
+utricularia('holtzei')
+utricularia('humboldtii')
+utricularia('huntii')
+utricularia('hydrocarpa')
+utricularia('inaequalis')
+utricularia('incisa')
+utricularia('inflata')
+utricularia('inflexa')
+utricularia('intermedia')
+utricularia('inthanonensis')
+utricularia('involvens')
+utricularia('jackii')
+utricularia('jamesoniana')
+utricularia('janarthanamii')
+utricularia('jobsonii')
+utricularia('juncea')
+utricularia('kamienskii')
+utricularia('kenneallyi')
+utricularia('kimberleyensis')
+utricularia('kumaonensis')
+utricularia('laciniata')
+utricularia('lasiocaulis')
+utricularia('lateriflora')
+utricularia('laxa')
+utricularia('lazulina')
+utricularia('leptoplectra')
+utricularia('leptorhyncha')
+utricularia('letestui')
+utricularia('limosa')
+utricularia('linearis')
+utricularia('livida')
+utricularia('livida f. mexico')
+utricularia('lloydii')
+utricularia('longeciliata')
+utricularia('longifolia')
+utricularia('longifolia f. bonsai')
+utricularia('longifolia var. forgetiana')
+utricularia('lowriei')
+utricularia('macrocheilos')
+utricularia('macrorhiza')
+utricularia('malabarica')
+utricularia('mangshanensis')
+utricularia('mannii')
+utricularia('menziesii')
+utricularia('meyeri')
+utricularia('microcalyx')
+utricularia('micropetala')
+utricularia('minor')
+utricularia('minutissima')
+utricularia('mirabilis')
+utricularia('monanthos')
+utricularia('moniliformis')
+utricularia('muelleri')
+utricularia('multicaulis')
+utricularia('multifida')
+utricularia('myriocista')
+utricularia('naikii')
+utricularia('nana')
+utricularia('naviculata')
+utricularia('nelumbifolia')
+utricularia('neottioides')
+utricularia('nephrophylla')
+utricularia('nervosa')
+utricularia('nigrescens')
+utricularia('nivea')
+utricularia('novae-zelandiae')
+utricularia('ochroleuca')
+utricularia('odontosepala')
+utricularia('odorata')
+utricularia('olivacea')
+utricularia('oliveriana')
+utricularia('panamensis')
+utricularia('parthenopipes')
+utricularia('paulineae')
+utricularia('peltata')
+utricularia('pentadactyla')
+utricularia('peranomala')
+utricularia('perversa')
+utricularia('petersoniae')
+utricularia('petertaylorii')
+utricularia('phusoidaoensis')
+utricularia('physoceras')
+utricularia('pierrei')
+utricularia('platensis')
+utricularia('pobeguinii')
+utricularia('poconensis')
+utricularia('podadena')
+utricularia('polygaloides')
+utricularia('praelonga')
+utricularia('praeterita')
+utricularia('praetermissa')
+utricularia('prehensilis')
+utricularia('protrusa')
+utricularia('pubescens')
+utricularia('pulchra')
+utricularia('punctata')
+utricularia('purpurascens')
+utricularia('purpurea')
+utricularia('purpureocaerulea')
+utricularia('pusilla')
+utricularia('quelchii')
+utricularia('quinquedentata')
+utricularia('racemosa')
+utricularia('radiata')
+utricularia('ramosissima')
+utricularia('raynalii')
+utricularia('recta')
+utricularia('reflexa')
+utricularia('regia')
+utricularia('reniformis')
+utricularia('resupinata')
+utricularia('reticulata')
+utricularia('rhododactylos')
+utricularia('rigida')
+utricularia('rostrata')
+utricularia('salwinensis')
+utricularia('sandersonii')
+utricularia('sandwithii')
+utricularia('scandens')
+utricularia('schultesii')
+utricularia('simmonsii')
+utricularia('simplex')
+utricularia('simulans')
+utricularia('singeriana')
+utricularia('smithiana')
+utricularia('spinomarginata')
+utricularia('spiralis')
+utricularia('spruceana')
+utricularia('stanfieldii')
+utricularia('steenisii')
+utricularia('stellaris')
+utricularia('steyermarkii')
+utricularia('striata')
+utricularia('striatula')
+utricularia('stygia')
+utricularia('subramanyamii')
+utricularia('subulata')
+utricularia('tenella')
+utricularia('tenuissima')
+utricularia('terrae-reginae')
+utricularia('tetraloba')
+utricularia('tortilis')
+utricularia('trichophylla')
+utricularia('tricolor')
+utricularia('tridactyla')
+utricularia('tridentata')
+utricularia('triflora')
+utricularia('triloba')
+utricularia('troupinii')
+utricularia('tubulata')
+utricularia('uliginosa')
+utricularia('uliginosa f. albida')
+utricularia('uniflora')
+utricularia('unifolia')
+utricularia('uxoris')
+utricularia('violacea')
+utricularia('viscosa')
+utricularia('vitellina')
+utricularia('volubilis')
+utricularia('vulgaris')
+utricularia('wannanii')
+utricularia('warburgii')
+utricularia('warmingii')
+utricularia('welwitschii')
+utricularia('westonii')
+utricularia('wightiana')








